### ISSUE TITLE
Crashing on received Message

### ISSUE THREAD

**Issue by CodeStrings** [toanphung/socket_flutter_plugin#3]
Everything works fine until the first message comes back:

`E/AndroidRuntime( 7699): java.lang.ClassCastException: org.json.JSONObject cannot be cast to java.lang.String
E/AndroidRuntime( 7699): 	at net.ongbut.socketflutterplugin.SocketFlutterPlugin$1.call(SocketFlutterPlugin.java:91)
E/AndroidRuntime( 7699): 	at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
E/AndroidRuntime( 7699): 	at com.github.nkzawa.socketio.client.Socket.onevent(Socket.java:308)
E/AndroidRuntime( 7699): 	at com.github.nkzawa.socketio.client.Socket.onpacket(Socket.java:272)
E/AndroidRuntime( 7699): 	at com.github.nkzawa.socketio.client.Socket.access$100(Socket.java:18)
E/AndroidRuntime( 7699): 	at com.github.nkzawa.socketio.client.Socket$2$2.call(Socket.java:99)
E/AndroidRuntime( 7699): 	at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
E/AndroidRuntime( 7699): 	at com.github.nkzawa.socketio.client.Manager.ondecoded(Manager.java:347)
E/AndroidRuntime( 7699): 	at com.github.nkzawa.socketio.client.Manager.access$1300(Manager.java:19)
E/AndroidRuntime( 7699): 	at com.github.nkzawa.socketio.client.Manager$3.call(Manager.java:321)
E/AndroidRuntime( 7699): 	at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
E/AndroidRuntime( 7699): 	at com.github.nkzawa.socketio.parser.Parser$Decoder.add(Parser.java:156)
E/AndroidRuntime( 7699): 	at com.github.nkzawa.socketio.client.Manager.ondata(Manager.java:339)
E/AndroidRuntime( 7699): 	at com.github.nkzawa.socketio.client.Manager.access$1100(Manager.java:19)
E/AndroidRuntime( 7699): 	at com.github.nkzawa.socketio.client.Manager$2.call(Manager.java:312)
E/AndroidRuntime( 7699): 	at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
E/AndroidRuntime( 7699): 	at com.github.nkzawa.engineio.client.Socket.onPacket(Socket.java:482)
E/AndroidRuntime( 7699): 	at com.github.nkzawa.engineio.client.Socket.access$800(Socket.java:29)
E/AndroidRuntime( 7699): 	at com.github.nkzawa.engineio.client.Socket$5.call(Socket.java:285)
E/AndroidRuntime( 7699): 	at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
E/AndroidRuntime( 7699): 	at com.github.nkzawa.engineio.client.Transport.onPacket(Transport.java:121)
E/AndroidRuntime( 7699): 	at com.github.nkzawa.engineio.client.Transport.onData(Transport.java:113)
E/AndroidRuntime( 7699): 	at com.github.nkzawa.engineio.client.transports.WebSocket.access$100(WebSocket.java:19)
E/AndroidRuntime( 7699): 	at com.github.nkzawa.engineio.client.transports.WebSocket$1$3.run(WebSocket.java:74)
E/AndroidRuntime( 7699): 	at com.github.nkzawa.thread.EventThread$2.run(EventThread.java:75)
E/AndroidRuntime( 7699): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
E/AndroidRuntime( 7699): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
E/AndroidRuntime( 7699): 	at java.lang.Thread.run(Thread.java:776)
I/Process ( 7699): Sending signal. PID: 7699 SIG: 9
Lost connection to device.`

**Comment by toanphung** [comment]
You should use json instead string.
Example: {'content': 'test'} instead 'test'.
My english not good. I hope you understand.

* Toan Phung Van*


* Bạn hỏi - Bụt trả lời*
* Cell:      *
*+84 988992298 <+84988992298> <%2B84%2094%20338%203315>*

* Skype:   toanphungv*

* Website: http://ongbut.net <http://ongbut.net>*
* Email:    toanphungv@gmail.com <toanphungv@gmail.com>*


Vào Th 4, 16 thg 1, 2019 vào lúc 23:50 Yonathan <notifications@github.com>
đã viết:
